import { useState } from 'react'
import { API_BASE } from '../api'

const CATEGORIES = ['technology', 'sports', 'business', 'entertainment', 'science', 'lifestyle']

export default function AdminWorkflowPage() {
  const [form, setForm] = useState({ mode: 'full', generateImages: true, generateAudio: true, castMode: 'auto', visualStyle: 'animated', language: 'en-IN', maxArticlesPerCategory: 3, maxTotalStories: 12 })
  const [categories, setCategories] = useState(CATEGORIES)
  const [task, setTask] = useState(null)

  const toggleCategory = (category) => setCategories((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category])
  const run = async (event) => {
    event.preventDefault()
    const response = await fetch(`${API_BASE}/api/admin/workflows/daily`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, categories }) })
    setTask(await response.json())
  }

  return <main className="min-h-screen bg-[#08090b] px-5 py-10 text-white sm:px-10"><div className="mx-auto max-w-2xl"><a href="/" className="text-sm font-bold text-fuchsia-300">Back to StoryCast</a><h1 className="mt-8 text-4xl font-black">Daily workflow</h1><p className="mt-2 text-white/55">Fetch, curate, and publish one canonical daily episode run.</p><form onSubmit={run} className="mt-8 space-y-6 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><label className="block text-sm font-bold">Run date<input type="date" value={form.runDate || ''} onChange={(event) => setForm({ ...form, runDate: event.target.value || null })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white" /></label><label className="block text-sm font-bold">Mode<select value={form.mode} onChange={(event) => setForm({ ...form, mode: event.target.value })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white"><option value="full">Fetch and generate</option><option value="fetch_only">Fetch only</option><option value="generate_only">Generate from archive</option></select></label><div><p className="text-sm font-bold">Categories</p><div className="mt-3 flex flex-wrap gap-2">{CATEGORIES.map((category) => <label key={category} className="rounded-full border border-white/10 px-3 py-2 text-xs font-bold"><input type="checkbox" checked={categories.includes(category)} onChange={() => toggleCategory(category)} className="mr-2" />{category}</label>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">Stories per category<input type="number" min="1" value={form.maxArticlesPerCategory} onChange={(event) => setForm({ ...form, maxArticlesPerCategory: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white" /></label><label className="block text-sm font-bold">Total Stories Generated<input type="number" min="1" value={form.maxTotalStories} onChange={(event) => setForm({ ...form, maxTotalStories: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white" /></label></div><div className="flex gap-5 text-sm font-bold"><label><input type="checkbox" checked={form.generateImages} onChange={(event) => setForm({ ...form, generateImages: event.target.checked })} className="mr-2" />Images</label><label><input type="checkbox" checked={form.generateAudio} onChange={(event) => setForm({ ...form, generateAudio: event.target.checked })} className="mr-2" />Audio</label></div><button className="rounded-xl bg-gradient-to-r from-fuchsia-600 to-pink-500 px-5 py-3 text-sm font-black">Run daily workflow</button></form>{task && <pre className="mt-6 overflow-auto rounded-2xl bg-black/30 p-4 text-xs text-white/70">{JSON.stringify(task, null, 2)}</pre>}</div></main>
}
